# -*- coding: utf-8 -*-
"""딥러닝을 위한 도구.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFEUwdM1C-AOpWikrSwVSKRBM6dlcOf5
"""

#numpy
import numpy as np
my_arr = np.array([[10, 20, 30], [40, 50, 60]]) #2차원 배열
print(my_arr)

my_arr[0][2]

np.sum(my_arr)

#matplotlib
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4, 5], [1, 4, 9, 16, 25])  #x축, y축의 값을 파이썬 리스트로 전달한다.
plt.show()

plt.scatter([1, 2, 3, 4, 5], [1, 4, 9, 16, 25])

x = np.random.randn(1000) #표준 정규 분포를 따르는 난수 1000개를 만든다.
y = np.random.randn(1000)
plt.scatter(x, y)
plt.show()